name: publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.LIARA_API_TOKEN  }}
      - run: npm config set _authToken=${{ secrets.LIARA_API_TOKEN }}
      - run: npm publish
